# -*- coding: utf-8 -*-
# Copyright (C) 2014-2025 ALBA Synchrotron
#
# Authors: A. Estela Herguedas Alonso, Joaquin Gomez Sanchez
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_magnetism_absorption3Dreconstruction(object):
    def setupUi(self, magnetism_absorption3Dreconstruction):
        magnetism_absorption3Dreconstruction.setObjectName("magnetism_absorption3Dreconstruction")
        magnetism_absorption3Dreconstruction.resize(750, 850)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("magnetism_3Dreconstruction\\ALBA_positiu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        magnetism_absorption3Dreconstruction.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(magnetism_absorption3Dreconstruction)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.visualizationTomoRot_pushButton = QtWidgets.QPushButton(magnetism_absorption3Dreconstruction)
        self.visualizationTomoRot_pushButton.setObjectName("visualizationTomoRot_pushButton")
        self.execution_buttonGroup = QtWidgets.QButtonGroup(magnetism_absorption3Dreconstruction)
        self.execution_buttonGroup.setObjectName("execution_buttonGroup")
        self.execution_buttonGroup.addButton(self.visualizationTomoRot_pushButton)
        self.gridLayout.addWidget(self.visualizationTomoRot_pushButton, 13, 2, 1, 1)
        self.dsetAbsorptionTomoRot_comboBox = QtWidgets.QComboBox(magnetism_absorption3Dreconstruction)
        self.dsetAbsorptionTomoRot_comboBox.setObjectName("dsetAbsorptionTomoRot_comboBox")
        self.gridLayout.addWidget(self.dsetAbsorptionTomoRot_comboBox, 2, 2, 1, 1)
        self.dsetAnglesTomo_comboBox = QtWidgets.QComboBox(magnetism_absorption3Dreconstruction)
        self.dsetAnglesTomo_comboBox.setObjectName("dsetAnglesTomo_comboBox")
        self.gridLayout.addWidget(self.dsetAnglesTomo_comboBox, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.segmentationTomoRot_pushButton = QtWidgets.QPushButton(magnetism_absorption3Dreconstruction)
        self.segmentationTomoRot_pushButton.setObjectName("segmentationTomoRot_pushButton")
        self.execution_buttonGroup.addButton(self.segmentationTomoRot_pushButton)
        self.gridLayout.addWidget(self.segmentationTomoRot_pushButton, 12, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.visualizationTomo_pushButton = QtWidgets.QPushButton(magnetism_absorption3Dreconstruction)
        self.visualizationTomo_pushButton.setObjectName("visualizationTomo_pushButton")
        self.execution_buttonGroup.addButton(self.visualizationTomo_pushButton)
        self.gridLayout.addWidget(self.visualizationTomo_pushButton, 13, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileHDF5TomoRot_lineEdit = QtWidgets.QLineEdit(magnetism_absorption3Dreconstruction)
        self.fileHDF5TomoRot_lineEdit.setObjectName("fileHDF5TomoRot_lineEdit")
        self.horizontalLayout_2.addWidget(self.fileHDF5TomoRot_lineEdit)
        self.selectFileHDF5TomoRot_toolButton = QtWidgets.QToolButton(magnetism_absorption3Dreconstruction)
        self.selectFileHDF5TomoRot_toolButton.setObjectName("selectFileHDF5TomoRot_toolButton")
        self.horizontalLayout_2.addWidget(self.selectFileHDF5TomoRot_toolButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 2, 1, 1)
        self.segmentationModeTomoRot_comboBox = QtWidgets.QComboBox(magnetism_absorption3Dreconstruction)
        self.segmentationModeTomoRot_comboBox.setObjectName("segmentationModeTomoRot_comboBox")
        self.segmentationModeTomoRot_comboBox.addItem("")
        self.segmentationModeTomoRot_comboBox.addItem("")
        self.segmentationModeTomoRot_comboBox.addItem("")
        self.gridLayout.addWidget(self.segmentationModeTomoRot_comboBox, 6, 2, 1, 1)
        self.negMaskTomoRot_checkBox = QtWidgets.QCheckBox(magnetism_absorption3Dreconstruction)
        self.negMaskTomoRot_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.negMaskTomoRot_checkBox.setText("")
        self.negMaskTomoRot_checkBox.setObjectName("negMaskTomoRot_checkBox")
        self.gridLayout.addWidget(self.negMaskTomoRot_checkBox, 8, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.outputNameTomo_lineEdit = QtWidgets.QLineEdit(magnetism_absorption3Dreconstruction)
        self.outputNameTomo_lineEdit.setObjectName("outputNameTomo_lineEdit")
        self.horizontalLayout_3.addWidget(self.outputNameTomo_lineEdit)
        self.label_8 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 1, 1, 1)
        self.dsetAbsorptionTomo_comboBox = QtWidgets.QComboBox(magnetism_absorption3Dreconstruction)
        self.dsetAbsorptionTomo_comboBox.setObjectName("dsetAbsorptionTomo_comboBox")
        self.gridLayout.addWidget(self.dsetAbsorptionTomo_comboBox, 2, 1, 1, 1)
        self.reconstructionTomoRot_pushButton = QtWidgets.QPushButton(magnetism_absorption3Dreconstruction)
        self.reconstructionTomoRot_pushButton.setObjectName("reconstructionTomoRot_pushButton")
        self.execution_buttonGroup.addButton(self.reconstructionTomoRot_pushButton)
        self.gridLayout.addWidget(self.reconstructionTomoRot_pushButton, 11, 2, 1, 1)
        self.negMaskTomo_checkBox = QtWidgets.QCheckBox(magnetism_absorption3Dreconstruction)
        self.negMaskTomo_checkBox.setText("")
        self.negMaskTomo_checkBox.setObjectName("negMaskTomo_checkBox")
        self.gridLayout.addWidget(self.negMaskTomo_checkBox, 8, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileHDF5Tomo_lineEdit = QtWidgets.QLineEdit(magnetism_absorption3Dreconstruction)
        self.fileHDF5Tomo_lineEdit.setObjectName("fileHDF5Tomo_lineEdit")
        self.horizontalLayout.addWidget(self.fileHDF5Tomo_lineEdit)
        self.selectFileHDF5Tomo_toolButton = QtWidgets.QToolButton(magnetism_absorption3Dreconstruction)
        self.selectFileHDF5Tomo_toolButton.setObjectName("selectFileHDF5Tomo_toolButton")
        self.horizontalLayout.addWidget(self.selectFileHDF5Tomo_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.threshValTomo_comboBox = QtWidgets.QComboBox(magnetism_absorption3Dreconstruction)
        self.threshValTomo_comboBox.setObjectName("threshValTomo_comboBox")
        self.threshValTomo_comboBox.addItem("")
        self.threshValTomo_comboBox.addItem("")
        self.threshValTomo_comboBox.addItem("")
        self.threshValTomo_comboBox.addItem("")
        self.threshValTomo_comboBox.addItem("")
        self.gridLayout.addWidget(self.threshValTomo_comboBox, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outputNameTomoRot_lineEdit = QtWidgets.QLineEdit(magnetism_absorption3Dreconstruction)
        self.outputNameTomoRot_lineEdit.setObjectName("outputNameTomoRot_lineEdit")
        self.horizontalLayout_4.addWidget(self.outputNameTomoRot_lineEdit)
        self.label_9 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.segmentationTomo_pushButton = QtWidgets.QPushButton(magnetism_absorption3Dreconstruction)
        self.segmentationTomo_pushButton.setObjectName("segmentationTomo_pushButton")
        self.execution_buttonGroup.addButton(self.segmentationTomo_pushButton)
        self.gridLayout.addWidget(self.segmentationTomo_pushButton, 12, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.segmentationModeTomo_comboBox = QtWidgets.QComboBox(magnetism_absorption3Dreconstruction)
        self.segmentationModeTomo_comboBox.setObjectName("segmentationModeTomo_comboBox")
        self.segmentationModeTomo_comboBox.addItem("")
        self.segmentationModeTomo_comboBox.addItem("")
        self.segmentationModeTomo_comboBox.addItem("")
        self.gridLayout.addWidget(self.segmentationModeTomo_comboBox, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.threshValTomoRot_comboBox = QtWidgets.QComboBox(magnetism_absorption3Dreconstruction)
        self.threshValTomoRot_comboBox.setObjectName("threshValTomoRot_comboBox")
        self.threshValTomoRot_comboBox.addItem("")
        self.threshValTomoRot_comboBox.addItem("")
        self.threshValTomoRot_comboBox.addItem("")
        self.threshValTomoRot_comboBox.addItem("")
        self.threshValTomoRot_comboBox.addItem("")
        self.gridLayout.addWidget(self.threshValTomoRot_comboBox, 7, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.reconstructionTomo_pushButton = QtWidgets.QPushButton(magnetism_absorption3Dreconstruction)
        self.reconstructionTomo_pushButton.setToolTip("")
        self.reconstructionTomo_pushButton.setObjectName("reconstructionTomo_pushButton")
        self.execution_buttonGroup.addButton(self.reconstructionTomo_pushButton)
        self.gridLayout.addWidget(self.reconstructionTomo_pushButton, 11, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.dsetAnglesTomoRot_comboBox = QtWidgets.QComboBox(magnetism_absorption3Dreconstruction)
        self.dsetAnglesTomoRot_comboBox.setObjectName("dsetAnglesTomoRot_comboBox")
        self.gridLayout.addWidget(self.dsetAnglesTomoRot_comboBox, 3, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.outputPathTomo_lineEdit = QtWidgets.QLineEdit(magnetism_absorption3Dreconstruction)
        self.outputPathTomo_lineEdit.setObjectName("outputPathTomo_lineEdit")
        self.horizontalLayout_5.addWidget(self.outputPathTomo_lineEdit)
        self.selectOutputPathTomo_toolButton = QtWidgets.QToolButton(magnetism_absorption3Dreconstruction)
        self.selectOutputPathTomo_toolButton.setObjectName("selectOutputPathTomo_toolButton")
        self.horizontalLayout_5.addWidget(self.selectOutputPathTomo_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.outputPathTomoRot_lineEdit = QtWidgets.QLineEdit(magnetism_absorption3Dreconstruction)
        self.outputPathTomoRot_lineEdit.setObjectName("outputPathTomoRot_lineEdit")
        self.horizontalLayout_9.addWidget(self.outputPathTomoRot_lineEdit)
        self.selectOutputPathTomoRot_toolButton = QtWidgets.QToolButton(magnetism_absorption3Dreconstruction)
        self.selectOutputPathTomoRot_toolButton.setObjectName("selectOutputPathTomoRot_toolButton")
        self.horizontalLayout_9.addWidget(self.selectOutputPathTomoRot_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.widget = QtWidgets.QWidget(magnetism_absorption3Dreconstruction)
        self.widget.setEnabled(True)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.GPU_checkBox = QtWidgets.QCheckBox(self.widget)
        self.GPU_checkBox.setText("")
        self.GPU_checkBox.setObjectName("GPU_checkBox")
        self.gridLayout_3.addWidget(self.GPU_checkBox, 6, 1, 1, 1)
        self.pixelSize_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.pixelSize_doubleSpinBox.setMinimum(0.0)
        self.pixelSize_doubleSpinBox.setProperty("value", 10.0)
        self.pixelSize_doubleSpinBox.setObjectName("pixelSize_doubleSpinBox")
        self.gridLayout_3.addWidget(self.pixelSize_doubleSpinBox, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 8, 0, 1, 1)
        self.useProjMat_checkBox = QtWidgets.QCheckBox(self.widget)
        self.useProjMat_checkBox.setText("")
        self.useProjMat_checkBox.setObjectName("useProjMat_checkBox")
        self.gridLayout_3.addWidget(self.useProjMat_checkBox, 8, 1, 1, 1)
        self.saveProjMat_checkBox = QtWidgets.QCheckBox(self.widget)
        self.saveProjMat_checkBox.setText("")
        self.saveProjMat_checkBox.setObjectName("saveProjMat_checkBox")
        self.gridLayout_3.addWidget(self.saveProjMat_checkBox, 7, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 5, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 4, 0, 1, 1)
        self.LCFlag_checkBox = QtWidgets.QCheckBox(self.widget)
        self.LCFlag_checkBox.setText("")
        self.LCFlag_checkBox.setObjectName("LCFlag_checkBox")
        self.gridLayout_3.addWidget(self.LCFlag_checkBox, 3, 1, 1, 1)
        self.simultSlcs_spinBox = QtWidgets.QSpinBox(self.widget)
        self.simultSlcs_spinBox.setMinimum(1)
        self.simultSlcs_spinBox.setMaximum(1000)
        self.simultSlcs_spinBox.setObjectName("simultSlcs_spinBox")
        self.gridLayout_3.addWidget(self.simultSlcs_spinBox, 5, 1, 1, 1)
        self.recAxis_comboBox = QtWidgets.QComboBox(self.widget)
        self.recAxis_comboBox.setObjectName("recAxis_comboBox")
        self.recAxis_comboBox.addItem("")
        self.recAxis_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.recAxis_comboBox, 4, 1, 1, 1)
        self.nIter_spinBox = QtWidgets.QSpinBox(self.widget)
        self.nIter_spinBox.setProperty("value", 20)
        self.nIter_spinBox.setObjectName("nIter_spinBox")
        self.gridLayout_3.addWidget(self.nIter_spinBox, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 6, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.modSxTomo_spinBox = QtWidgets.QSpinBox(self.widget)
        self.modSxTomo_spinBox.setMaximum(1000000)
        self.modSxTomo_spinBox.setObjectName("modSxTomo_spinBox")
        self.horizontalLayout_7.addWidget(self.modSxTomo_spinBox)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.modSyTomo_spinBox = QtWidgets.QSpinBox(self.widget)
        self.modSyTomo_spinBox.setMaximum(100000)
        self.modSyTomo_spinBox.setObjectName("modSyTomo_spinBox")
        self.horizontalLayout_7.addWidget(self.modSyTomo_spinBox)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.modSzTomo_spinBox = QtWidgets.QSpinBox(self.widget)
        self.modSzTomo_spinBox.setMaximum(100000)
        self.modSzTomo_spinBox.setProperty("value", 200)
        self.modSzTomo_spinBox.setObjectName("modSzTomo_spinBox")
        self.horizontalLayout_7.addWidget(self.modSzTomo_spinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.notes = QtWidgets.QTextEdit(magnetism_absorption3Dreconstruction)
        self.notes.setEnabled(True)
        self.notes.setObjectName("notes")
        self.verticalLayout.addWidget(self.notes)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_19 = QtWidgets.QLabel(magnetism_absorption3Dreconstruction)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)

        self.retranslateUi(magnetism_absorption3Dreconstruction)
        QtCore.QMetaObject.connectSlotsByName(magnetism_absorption3Dreconstruction)
        magnetism_absorption3Dreconstruction.setTabOrder(self.fileHDF5Tomo_lineEdit, self.selectFileHDF5Tomo_toolButton)
        magnetism_absorption3Dreconstruction.setTabOrder(self.selectFileHDF5Tomo_toolButton, self.dsetAbsorptionTomo_comboBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.dsetAbsorptionTomo_comboBox, self.dsetAnglesTomo_comboBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.dsetAnglesTomo_comboBox, self.outputNameTomo_lineEdit)
        magnetism_absorption3Dreconstruction.setTabOrder(self.outputNameTomo_lineEdit, self.segmentationModeTomo_comboBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.segmentationModeTomo_comboBox, self.threshValTomo_comboBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.threshValTomo_comboBox, self.negMaskTomo_checkBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.negMaskTomo_checkBox, self.modSzTomo_spinBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.modSzTomo_spinBox, self.reconstructionTomo_pushButton)
        magnetism_absorption3Dreconstruction.setTabOrder(self.reconstructionTomo_pushButton, self.segmentationTomo_pushButton)
        magnetism_absorption3Dreconstruction.setTabOrder(self.segmentationTomo_pushButton, self.visualizationTomo_pushButton)
        magnetism_absorption3Dreconstruction.setTabOrder(self.visualizationTomo_pushButton, self.fileHDF5TomoRot_lineEdit)
        magnetism_absorption3Dreconstruction.setTabOrder(self.fileHDF5TomoRot_lineEdit, self.selectFileHDF5TomoRot_toolButton)
        magnetism_absorption3Dreconstruction.setTabOrder(self.selectFileHDF5TomoRot_toolButton, self.dsetAbsorptionTomoRot_comboBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.dsetAbsorptionTomoRot_comboBox, self.dsetAnglesTomoRot_comboBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.dsetAnglesTomoRot_comboBox, self.outputNameTomoRot_lineEdit)
        magnetism_absorption3Dreconstruction.setTabOrder(self.outputNameTomoRot_lineEdit, self.segmentationModeTomoRot_comboBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.segmentationModeTomoRot_comboBox, self.threshValTomoRot_comboBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.threshValTomoRot_comboBox, self.negMaskTomoRot_checkBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.negMaskTomoRot_checkBox, self.reconstructionTomoRot_pushButton)
        magnetism_absorption3Dreconstruction.setTabOrder(self.reconstructionTomoRot_pushButton, self.segmentationTomoRot_pushButton)
        magnetism_absorption3Dreconstruction.setTabOrder(self.segmentationTomoRot_pushButton, self.visualizationTomoRot_pushButton)
        magnetism_absorption3Dreconstruction.setTabOrder(self.visualizationTomoRot_pushButton, self.nIter_spinBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.nIter_spinBox, self.LCFlag_checkBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.LCFlag_checkBox, self.recAxis_comboBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.recAxis_comboBox, self.simultSlcs_spinBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.simultSlcs_spinBox, self.GPU_checkBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.GPU_checkBox, self.saveProjMat_checkBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.saveProjMat_checkBox, self.useProjMat_checkBox)
        magnetism_absorption3Dreconstruction.setTabOrder(self.useProjMat_checkBox, self.notes)

    def retranslateUi(self, magnetism_absorption3Dreconstruction):
        _translate = QtCore.QCoreApplication.translate
        magnetism_absorption3Dreconstruction.setWindowTitle(_translate("magnetism_absorption3Dreconstruction", "MARTApp"))
        self.label.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Compute the reconstruction of the absorption 3D aligned for 3D magnetic structures and obtain a 3D mask with segmentation."))
        self.label.setText(_translate("magnetism_absorption3Dreconstruction", "Absorption reconstruction of 3D samples"))
        self.visualizationTomoRot_pushButton.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Open HDF5 for visualization with Napari"))
        self.visualizationTomoRot_pushButton.setText(_translate("magnetism_absorption3Dreconstruction", "Visualization"))
        self.label_7.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Beggining of the output filename with the reconstruction results."))
        self.label_7.setText(_translate("magnetism_absorption3Dreconstruction", "Output\n"
"filename"))
        self.label_10.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Type of segmentation."))
        self.label_10.setText(_translate("magnetism_absorption3Dreconstruction", "Segmentation\n"
"mode"))
        self.segmentationTomoRot_pushButton.setText(_translate("magnetism_absorption3Dreconstruction", "Only Segmentation"))
        self.label_3.setText(_translate("magnetism_absorption3Dreconstruction", "Tomo Rot"))
        self.visualizationTomo_pushButton.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Open HDF5 for visualization with Napari"))
        self.visualizationTomo_pushButton.setText(_translate("magnetism_absorption3Dreconstruction", "Visualization"))
        self.selectFileHDF5TomoRot_toolButton.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Select HDF5 file for tomo rotated"))
        self.selectFileHDF5TomoRot_toolButton.setText(_translate("magnetism_absorption3Dreconstruction", "..."))
        self.segmentationModeTomoRot_comboBox.setItemText(0, _translate("magnetism_absorption3Dreconstruction", "Threshold"))
        self.segmentationModeTomoRot_comboBox.setItemText(1, _translate("magnetism_absorption3Dreconstruction", "2D_symmetry"))
        self.segmentationModeTomoRot_comboBox.setItemText(2, _translate("magnetism_absorption3Dreconstruction", "Continous_film"))
        self.label_8.setText(_translate("magnetism_absorption3Dreconstruction", "_AbsorptionReconstruction.hdf5"))
        self.reconstructionTomoRot_pushButton.setText(_translate("magnetism_absorption3Dreconstruction", "Reconstruction+Segmentation"))
        self.selectFileHDF5Tomo_toolButton.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Select HDF5 for tomo"))
        self.selectFileHDF5Tomo_toolButton.setText(_translate("magnetism_absorption3Dreconstruction", "..."))
        self.threshValTomo_comboBox.setItemText(0, _translate("magnetism_absorption3Dreconstruction", "Manual"))
        self.threshValTomo_comboBox.setItemText(1, _translate("magnetism_absorption3Dreconstruction", "Otsu"))
        self.threshValTomo_comboBox.setItemText(2, _translate("magnetism_absorption3Dreconstruction", "Triangle"))
        self.threshValTomo_comboBox.setItemText(3, _translate("magnetism_absorption3Dreconstruction", "Huang"))
        self.threshValTomo_comboBox.setItemText(4, _translate("magnetism_absorption3Dreconstruction", "MaxEntropy"))
        self.label_4.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Filename of the HDF5 that contains the Absorption images and the angles"))
        self.label_4.setText(_translate("magnetism_absorption3Dreconstruction", "HDF5 file"))
        self.label_9.setText(_translate("magnetism_absorption3Dreconstruction", "_AbsorptionReconstruction.hdf5"))
        self.label_6.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Dataset of the angles matching the absorption images."))
        self.label_6.setText(_translate("magnetism_absorption3Dreconstruction", "Dataset\n"
"Angles"))
        self.segmentationTomo_pushButton.setText(_translate("magnetism_absorption3Dreconstruction", "Only Segmentation"))
        self.label_12.setText(_translate("magnetism_absorption3Dreconstruction", "Negative\n"
"mask"))
        self.label_2.setText(_translate("magnetism_absorption3Dreconstruction", "Tomo"))
        self.segmentationModeTomo_comboBox.setItemText(0, _translate("magnetism_absorption3Dreconstruction", "Threshold"))
        self.segmentationModeTomo_comboBox.setItemText(1, _translate("magnetism_absorption3Dreconstruction", "2D_symmetry"))
        self.segmentationModeTomo_comboBox.setItemText(2, _translate("magnetism_absorption3Dreconstruction", "Continous_film"))
        self.label_14.setText(_translate("magnetism_absorption3Dreconstruction", "Output\n"
"path"))
        self.threshValTomoRot_comboBox.setItemText(0, _translate("magnetism_absorption3Dreconstruction", "Manual"))
        self.threshValTomoRot_comboBox.setItemText(1, _translate("magnetism_absorption3Dreconstruction", "Otsu"))
        self.threshValTomoRot_comboBox.setItemText(2, _translate("magnetism_absorption3Dreconstruction", "Triangle"))
        self.threshValTomoRot_comboBox.setItemText(3, _translate("magnetism_absorption3Dreconstruction", "Huang"))
        self.threshValTomoRot_comboBox.setItemText(4, _translate("magnetism_absorption3Dreconstruction", "MaxEntropy"))
        self.label_11.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Choose between algorithms to obtain the threshold value"))
        self.label_11.setText(_translate("magnetism_absorption3Dreconstruction", "Threshold\n"
"value"))
        self.reconstructionTomo_pushButton.setText(_translate("magnetism_absorption3Dreconstruction", "Reconstruction+Segmentation"))
        self.label_5.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Dataset of the absorption images 3D aligned"))
        self.label_5.setText(_translate("magnetism_absorption3Dreconstruction", "Dataset\n"
"Absorption\n"
"3DAligned"))
        self.selectOutputPathTomo_toolButton.setText(_translate("magnetism_absorption3Dreconstruction", "..."))
        self.selectOutputPathTomoRot_toolButton.setText(_translate("magnetism_absorption3Dreconstruction", "..."))
        self.label_22.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Number of iterations for the reconstruction algorithm"))
        self.label_22.setText(_translate("magnetism_absorption3Dreconstruction", "Number iterations"))
        self.label_28.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Only activate id there is stored the pre-computed reconstruction matrices.\n"
"These should be stored inside the working directory in a folder called \'Projection_Matrices\'.\n"
"The name of each block of matrices should be \'Projection_x.mat\' with x being the projection number."))
        self.label_28.setText(_translate("magnetism_absorption3Dreconstruction", "Use Projection Matrices"))
        self.label_23.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Indicate if it is a continuous film."))
        self.label_23.setText(_translate("magnetism_absorption3Dreconstruction", "Continuous film"))
        self.label_25.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Number of simultaneous slices to reconstruct.\n"
"This increases the performance of the reconstruction if there is enough memory available to speed-up the reconstruction."))
        self.label_25.setText(_translate("magnetism_absorption3Dreconstruction", "Simultaneous Slices"))
        self.label_27.setText(_translate("magnetism_absorption3Dreconstruction", "Save Projection Matrices"))
        self.label_13.setText(_translate("magnetism_absorption3Dreconstruction", "Pixel size (nm)"))
        self.label_24.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Indicate if the reconstruction is performed by rotating the X or the Y axis.\n"
"The first means an stretching in the vertical direction,\n"
"the second, in the horizontal."))
        self.label_24.setText(_translate("magnetism_absorption3Dreconstruction", "Reconstruction Axis"))
        self.recAxis_comboBox.setItemText(0, _translate("magnetism_absorption3Dreconstruction", "YTilt"))
        self.recAxis_comboBox.setItemText(1, _translate("magnetism_absorption3Dreconstruction", "XTilt"))
        self.label_26.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Only mark if a Nvidia GPU is available with CUDA installed"))
        self.label_26.setText(_translate("magnetism_absorption3Dreconstruction", "GPU"))
        self.label_15.setToolTip(_translate("magnetism_absorption3Dreconstruction", "Number of cells for the reconstruction in X, Y and Z.\n"
"It can be as larga as the number of rows and columns in the input tomogram.\n"
"If X or Y is 0, it takes the size of the absorption images. "))
        self.label_15.setText(_translate("magnetism_absorption3Dreconstruction", "Number of\n"
"cells"))
        self.label_16.setText(_translate("magnetism_absorption3Dreconstruction", "X"))
        self.label_17.setText(_translate("magnetism_absorption3Dreconstruction", "Y"))
        self.label_18.setText(_translate("magnetism_absorption3Dreconstruction", "Z"))
        self.label_19.setText(_translate("magnetism_absorption3Dreconstruction", "Copyright © 2024 ALBA-CELLS"))
