# -*- coding: utf-8 -*-
# Copyright (C) 2014-2025 ALBA Synchrotron
#
# Authors: A. Estela Herguedas Alonso, Joaquin Gomez Sanchez
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_magnetism_signal3Dreconstruction(object):
    def setupUi(self, magnetism_signal3Dreconstruction):
        magnetism_signal3Dreconstruction.setObjectName("magnetism_signal3Dreconstruction")
        magnetism_signal3Dreconstruction.resize(746, 850)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("magnetism_3Dreconstruction\\ALBA_positiu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        magnetism_signal3Dreconstruction.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(magnetism_signal3Dreconstruction)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.label_29 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.dsetAbsorptionTomoRot_comboBox = QtWidgets.QComboBox(magnetism_signal3Dreconstruction)
        self.dsetAbsorptionTomoRot_comboBox.setObjectName("dsetAbsorptionTomoRot_comboBox")
        self.gridLayout.addWidget(self.dsetAbsorptionTomoRot_comboBox, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.dsetMaskTomo_comboBox = QtWidgets.QComboBox(magnetism_signal3Dreconstruction)
        self.dsetMaskTomo_comboBox.setObjectName("dsetMaskTomo_comboBox")
        self.dsetMaskTomo_comboBox.addItem("")
        self.gridLayout.addWidget(self.dsetMaskTomo_comboBox, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.dsetAnglesTomoRot_comboBox = QtWidgets.QComboBox(magnetism_signal3Dreconstruction)
        self.dsetAnglesTomoRot_comboBox.setObjectName("dsetAnglesTomoRot_comboBox")
        self.gridLayout.addWidget(self.dsetAnglesTomoRot_comboBox, 3, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outputNameTomoRot_lineEdit = QtWidgets.QLineEdit(magnetism_signal3Dreconstruction)
        self.outputNameTomoRot_lineEdit.setObjectName("outputNameTomoRot_lineEdit")
        self.horizontalLayout_4.addWidget(self.outputNameTomoRot_lineEdit)
        self.label_9 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout_4, 7, 2, 1, 1)
        self.dsetMaskTomoRot_comboBox = QtWidgets.QComboBox(magnetism_signal3Dreconstruction)
        self.dsetMaskTomoRot_comboBox.setObjectName("dsetMaskTomoRot_comboBox")
        self.dsetMaskTomoRot_comboBox.addItem("")
        self.gridLayout.addWidget(self.dsetMaskTomoRot_comboBox, 5, 2, 1, 1)
        self.dsetAnglesTomo_comboBox = QtWidgets.QComboBox(magnetism_signal3Dreconstruction)
        self.dsetAnglesTomo_comboBox.setObjectName("dsetAnglesTomo_comboBox")
        self.gridLayout.addWidget(self.dsetAnglesTomo_comboBox, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.outputNameTomo_lineEdit = QtWidgets.QLineEdit(magnetism_signal3Dreconstruction)
        self.outputNameTomo_lineEdit.setObjectName("outputNameTomo_lineEdit")
        self.horizontalLayout_3.addWidget(self.outputNameTomo_lineEdit)
        self.label_8 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.fileMaskTomoRot_lineEdit = QtWidgets.QLineEdit(magnetism_signal3Dreconstruction)
        self.fileMaskTomoRot_lineEdit.setObjectName("fileMaskTomoRot_lineEdit")
        self.horizontalLayout_11.addWidget(self.fileMaskTomoRot_lineEdit)
        self.selectFileMaskTomoRot_toolButton = QtWidgets.QToolButton(magnetism_signal3Dreconstruction)
        self.selectFileMaskTomoRot_toolButton.setObjectName("selectFileMaskTomoRot_toolButton")
        self.horizontalLayout_11.addWidget(self.selectFileMaskTomoRot_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_11, 4, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileHDF5TomoRot_lineEdit = QtWidgets.QLineEdit(magnetism_signal3Dreconstruction)
        self.fileHDF5TomoRot_lineEdit.setObjectName("fileHDF5TomoRot_lineEdit")
        self.horizontalLayout_2.addWidget(self.fileHDF5TomoRot_lineEdit)
        self.selectFileHDF5TomoRot_toolButton = QtWidgets.QToolButton(magnetism_signal3Dreconstruction)
        self.selectFileHDF5TomoRot_toolButton.setObjectName("selectFileHDF5TomoRot_toolButton")
        self.horizontalLayout_2.addWidget(self.selectFileHDF5TomoRot_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.fileMaskTomo_lineEdit = QtWidgets.QLineEdit(magnetism_signal3Dreconstruction)
        self.fileMaskTomo_lineEdit.setObjectName("fileMaskTomo_lineEdit")
        self.horizontalLayout_10.addWidget(self.fileMaskTomo_lineEdit)
        self.selectFileMaskTomo_toolButton = QtWidgets.QToolButton(magnetism_signal3Dreconstruction)
        self.selectFileMaskTomo_toolButton.setObjectName("selectFileMaskTomo_toolButton")
        self.horizontalLayout_10.addWidget(self.selectFileMaskTomo_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileHDF5Tomo_lineEdit = QtWidgets.QLineEdit(magnetism_signal3Dreconstruction)
        self.fileHDF5Tomo_lineEdit.setObjectName("fileHDF5Tomo_lineEdit")
        self.horizontalLayout.addWidget(self.fileHDF5Tomo_lineEdit)
        self.selectFileHDF5Tomo_toolButton = QtWidgets.QToolButton(magnetism_signal3Dreconstruction)
        self.selectFileHDF5Tomo_toolButton.setObjectName("selectFileHDF5Tomo_toolButton")
        self.horizontalLayout.addWidget(self.selectFileHDF5Tomo_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.dsetAbsorptionTomo_comboBox = QtWidgets.QComboBox(magnetism_signal3Dreconstruction)
        self.dsetAbsorptionTomo_comboBox.setObjectName("dsetAbsorptionTomo_comboBox")
        self.gridLayout.addWidget(self.dsetAbsorptionTomo_comboBox, 2, 1, 1, 1)
        self.dsetMaskReg_comboBox = QtWidgets.QComboBox(magnetism_signal3Dreconstruction)
        self.dsetMaskReg_comboBox.setObjectName("dsetMaskReg_comboBox")
        self.gridLayout.addWidget(self.dsetMaskReg_comboBox, 6, 1, 1, 1)
        self.dsetMaskRegRot_comboBox = QtWidgets.QComboBox(magnetism_signal3Dreconstruction)
        self.dsetMaskRegRot_comboBox.setObjectName("dsetMaskRegRot_comboBox")
        self.gridLayout.addWidget(self.dsetMaskRegRot_comboBox, 6, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.widget = QtWidgets.QWidget(magnetism_signal3Dreconstruction)
        self.widget.setEnabled(True)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 8, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 7, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 6, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.GPU_checkBox = QtWidgets.QCheckBox(self.widget)
        self.GPU_checkBox.setText("")
        self.GPU_checkBox.setObjectName("GPU_checkBox")
        self.gridLayout_3.addWidget(self.GPU_checkBox, 7, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.outputPathTomo_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.outputPathTomo_lineEdit.setObjectName("outputPathTomo_lineEdit")
        self.horizontalLayout_8.addWidget(self.outputPathTomo_lineEdit)
        self.selectOutputPathTomo_toolButton = QtWidgets.QToolButton(self.widget)
        self.selectOutputPathTomo_toolButton.setObjectName("selectOutputPathTomo_toolButton")
        self.horizontalLayout_8.addWidget(self.selectOutputPathTomo_toolButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.recAxis_comboBox = QtWidgets.QComboBox(self.widget)
        self.recAxis_comboBox.setObjectName("recAxis_comboBox")
        self.recAxis_comboBox.addItem("")
        self.recAxis_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.recAxis_comboBox, 5, 1, 1, 1)
        self.pixelSize_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.pixelSize_doubleSpinBox.setMinimum(0.0)
        self.pixelSize_doubleSpinBox.setProperty("value", 10.0)
        self.pixelSize_doubleSpinBox.setObjectName("pixelSize_doubleSpinBox")
        self.gridLayout_3.addWidget(self.pixelSize_doubleSpinBox, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 9, 0, 1, 1)
        self.LCFlag_checkBox = QtWidgets.QCheckBox(self.widget)
        self.LCFlag_checkBox.setText("")
        self.LCFlag_checkBox.setObjectName("LCFlag_checkBox")
        self.gridLayout_3.addWidget(self.LCFlag_checkBox, 4, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.modSx_spinBox = QtWidgets.QSpinBox(self.widget)
        self.modSx_spinBox.setMaximum(100000)
        self.modSx_spinBox.setObjectName("modSx_spinBox")
        self.horizontalLayout_7.addWidget(self.modSx_spinBox)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.modSy_spinBox = QtWidgets.QSpinBox(self.widget)
        self.modSy_spinBox.setMaximum(100000)
        self.modSy_spinBox.setObjectName("modSy_spinBox")
        self.horizontalLayout_7.addWidget(self.modSy_spinBox)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.modSz_spinBox = QtWidgets.QSpinBox(self.widget)
        self.modSz_spinBox.setMaximum(100000)
        self.modSz_spinBox.setProperty("value", 200)
        self.modSz_spinBox.setObjectName("modSz_spinBox")
        self.horizontalLayout_7.addWidget(self.modSz_spinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.useProjMat_checkBox = QtWidgets.QCheckBox(self.widget)
        self.useProjMat_checkBox.setText("")
        self.useProjMat_checkBox.setObjectName("useProjMat_checkBox")
        self.gridLayout_3.addWidget(self.useProjMat_checkBox, 9, 1, 1, 1)
        self.saveProjMat_checkBox = QtWidgets.QCheckBox(self.widget)
        self.saveProjMat_checkBox.setText("")
        self.saveProjMat_checkBox.setObjectName("saveProjMat_checkBox")
        self.gridLayout_3.addWidget(self.saveProjMat_checkBox, 8, 1, 1, 1)
        self.nIter_spinBox = QtWidgets.QSpinBox(self.widget)
        self.nIter_spinBox.setProperty("value", 20)
        self.nIter_spinBox.setObjectName("nIter_spinBox")
        self.gridLayout_3.addWidget(self.nIter_spinBox, 3, 1, 1, 1)
        self.simultSlcs_spinBox = QtWidgets.QSpinBox(self.widget)
        self.simultSlcs_spinBox.setMinimum(1)
        self.simultSlcs_spinBox.setMaximum(1000)
        self.simultSlcs_spinBox.setObjectName("simultSlcs_spinBox")
        self.gridLayout_3.addWidget(self.simultSlcs_spinBox, 6, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 4, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.reconstruction_pushButton = QtWidgets.QPushButton(self.widget)
        self.reconstruction_pushButton.setObjectName("reconstruction_pushButton")
        self.execution_buttonGroup = QtWidgets.QButtonGroup(magnetism_signal3Dreconstruction)
        self.execution_buttonGroup.setObjectName("execution_buttonGroup")
        self.execution_buttonGroup.addButton(self.reconstruction_pushButton)
        self.horizontalLayout_6.addWidget(self.reconstruction_pushButton)
        self.registration_pushButton = QtWidgets.QPushButton(self.widget)
        self.registration_pushButton.setObjectName("registration_pushButton")
        self.execution_buttonGroup.addButton(self.registration_pushButton)
        self.horizontalLayout_6.addWidget(self.registration_pushButton)
        self.visualization_pushButton = QtWidgets.QPushButton(self.widget)
        self.visualization_pushButton.setObjectName("visualization_pushButton")
        self.execution_buttonGroup.addButton(self.visualization_pushButton)
        self.horizontalLayout_6.addWidget(self.visualization_pushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.notes = QtWidgets.QTextEdit(magnetism_signal3Dreconstruction)
        self.notes.setObjectName("notes")
        self.verticalLayout.addWidget(self.notes)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_11 = QtWidgets.QLabel(magnetism_signal3Dreconstruction)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)

        self.retranslateUi(magnetism_signal3Dreconstruction)
        QtCore.QMetaObject.connectSlotsByName(magnetism_signal3Dreconstruction)
        magnetism_signal3Dreconstruction.setTabOrder(self.fileHDF5Tomo_lineEdit, self.selectFileHDF5Tomo_toolButton)
        magnetism_signal3Dreconstruction.setTabOrder(self.selectFileHDF5Tomo_toolButton, self.dsetAbsorptionTomo_comboBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.dsetAbsorptionTomo_comboBox, self.dsetAnglesTomo_comboBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.dsetAnglesTomo_comboBox, self.fileMaskTomo_lineEdit)
        magnetism_signal3Dreconstruction.setTabOrder(self.fileMaskTomo_lineEdit, self.selectFileMaskTomo_toolButton)
        magnetism_signal3Dreconstruction.setTabOrder(self.selectFileMaskTomo_toolButton, self.dsetMaskTomo_comboBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.dsetMaskTomo_comboBox, self.outputNameTomo_lineEdit)
        magnetism_signal3Dreconstruction.setTabOrder(self.outputNameTomo_lineEdit, self.fileHDF5TomoRot_lineEdit)
        magnetism_signal3Dreconstruction.setTabOrder(self.fileHDF5TomoRot_lineEdit, self.selectFileHDF5TomoRot_toolButton)
        magnetism_signal3Dreconstruction.setTabOrder(self.selectFileHDF5TomoRot_toolButton, self.dsetAbsorptionTomoRot_comboBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.dsetAbsorptionTomoRot_comboBox, self.dsetAnglesTomoRot_comboBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.dsetAnglesTomoRot_comboBox, self.fileMaskTomoRot_lineEdit)
        magnetism_signal3Dreconstruction.setTabOrder(self.fileMaskTomoRot_lineEdit, self.selectFileMaskTomoRot_toolButton)
        magnetism_signal3Dreconstruction.setTabOrder(self.selectFileMaskTomoRot_toolButton, self.dsetMaskTomoRot_comboBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.dsetMaskTomoRot_comboBox, self.outputNameTomoRot_lineEdit)
        magnetism_signal3Dreconstruction.setTabOrder(self.outputNameTomoRot_lineEdit, self.outputPathTomo_lineEdit)
        magnetism_signal3Dreconstruction.setTabOrder(self.outputPathTomo_lineEdit, self.selectOutputPathTomo_toolButton)
        magnetism_signal3Dreconstruction.setTabOrder(self.selectOutputPathTomo_toolButton, self.modSz_spinBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.modSz_spinBox, self.pixelSize_doubleSpinBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.pixelSize_doubleSpinBox, self.nIter_spinBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.nIter_spinBox, self.LCFlag_checkBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.LCFlag_checkBox, self.recAxis_comboBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.recAxis_comboBox, self.simultSlcs_spinBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.simultSlcs_spinBox, self.GPU_checkBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.GPU_checkBox, self.saveProjMat_checkBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.saveProjMat_checkBox, self.useProjMat_checkBox)
        magnetism_signal3Dreconstruction.setTabOrder(self.useProjMat_checkBox, self.reconstruction_pushButton)
        magnetism_signal3Dreconstruction.setTabOrder(self.reconstruction_pushButton, self.registration_pushButton)
        magnetism_signal3Dreconstruction.setTabOrder(self.registration_pushButton, self.visualization_pushButton)
        magnetism_signal3Dreconstruction.setTabOrder(self.visualization_pushButton, self.notes)

    def retranslateUi(self, magnetism_signal3Dreconstruction):
        _translate = QtCore.QCoreApplication.translate
        magnetism_signal3Dreconstruction.setWindowTitle(_translate("magnetism_signal3Dreconstruction", "MARTApp"))
        self.label.setToolTip(_translate("magnetism_signal3Dreconstruction", "Compute the reconstruction of the absorption 3D aligned for 3D magnetic structures and obtain a 3D mask with segmentation."))
        self.label.setText(_translate("magnetism_signal3Dreconstruction", "Magnetic reconstruction of 3D samples"))
        self.label_29.setText(_translate("magnetism_signal3Dreconstruction", "HDF5 mask"))
        self.label_3.setText(_translate("magnetism_signal3Dreconstruction", "Tomo Rot"))
        self.label_2.setText(_translate("magnetism_signal3Dreconstruction", "Tomo"))
        self.label_30.setText(_translate("magnetism_signal3Dreconstruction", "Dataset Mask\n"
"(reconstruction)"))
        self.label_5.setToolTip(_translate("magnetism_signal3Dreconstruction", "Dataset of the absorption images 3D aligned"))
        self.label_5.setText(_translate("magnetism_signal3Dreconstruction", "Dataset\n"
"XMCD\n"
"3DAligned"))
        self.label_7.setToolTip(_translate("magnetism_signal3Dreconstruction", "Beggining of the output filename with the reconstruction results."))
        self.label_7.setText(_translate("magnetism_signal3Dreconstruction", "Output\n"
"filename"))
        self.label_4.setToolTip(_translate("magnetism_signal3Dreconstruction", "Filename of the HDF5 that contains the Absorption images and the angles"))
        self.label_4.setText(_translate("magnetism_signal3Dreconstruction", "HDF5 file"))
        self.dsetMaskTomo_comboBox.setItemText(0, _translate("magnetism_signal3Dreconstruction", "None"))
        self.label_6.setToolTip(_translate("magnetism_signal3Dreconstruction", "Dataset of the angles matching the absorption images."))
        self.label_6.setText(_translate("magnetism_signal3Dreconstruction", "Dataset\n"
"Angles"))
        self.label_9.setText(_translate("magnetism_signal3Dreconstruction", "_MagneticReconstruction.hdf5"))
        self.dsetMaskTomoRot_comboBox.setItemText(0, _translate("magnetism_signal3Dreconstruction", "None"))
        self.label_8.setText(_translate("magnetism_signal3Dreconstruction", "_MagneticReconstruction.hdf5"))
        self.selectFileMaskTomoRot_toolButton.setText(_translate("magnetism_signal3Dreconstruction", "..."))
        self.selectFileHDF5TomoRot_toolButton.setText(_translate("magnetism_signal3Dreconstruction", "..."))
        self.selectFileMaskTomo_toolButton.setText(_translate("magnetism_signal3Dreconstruction", "..."))
        self.selectFileHDF5Tomo_toolButton.setToolTip(_translate("magnetism_signal3Dreconstruction", "Select HDF5 for tomo"))
        self.selectFileHDF5Tomo_toolButton.setText(_translate("magnetism_signal3Dreconstruction", "..."))
        self.label_10.setText(_translate("magnetism_signal3Dreconstruction", "Dataset Mask\n"
"(registration)"))
        self.label_27.setText(_translate("magnetism_signal3Dreconstruction", "Save Projection Matrices"))
        self.label_26.setToolTip(_translate("magnetism_signal3Dreconstruction", "Only mark if a Nvidia GPU is available with CUDA installed"))
        self.label_26.setText(_translate("magnetism_signal3Dreconstruction", "GPU"))
        self.label_25.setToolTip(_translate("magnetism_signal3Dreconstruction", "Number of simultaneous slices to reconstruct.\n"
"This increases the performance of the reconstruction if there is enough memory available to speed-up the reconstruction."))
        self.label_25.setText(_translate("magnetism_signal3Dreconstruction", "Simultaneous Slices"))
        self.label_24.setToolTip(_translate("magnetism_signal3Dreconstruction", "Indicate if the reconstruction is performed by rotating the X or the Y axis.\n"
"The first means an stretching in the vertical direction,\n"
"the second, in the horizontal."))
        self.label_24.setText(_translate("magnetism_signal3Dreconstruction", "Reconstruction Axis"))
        self.label_13.setText(_translate("magnetism_signal3Dreconstruction", "Pixel size (nm)"))
        self.selectOutputPathTomo_toolButton.setText(_translate("magnetism_signal3Dreconstruction", "..."))
        self.recAxis_comboBox.setItemText(0, _translate("magnetism_signal3Dreconstruction", "YTilt"))
        self.recAxis_comboBox.setItemText(1, _translate("magnetism_signal3Dreconstruction", "XTilt"))
        self.label_28.setToolTip(_translate("magnetism_signal3Dreconstruction", "Only activate id there is stored the pre-computed reconstruction matrices.\n"
"These should be stored inside the working directory in a folder called \'Projection_Matrices\'.\n"
"The name of each block of matrices should be \'Projection_x.mat\' with x being the projection number."))
        self.label_28.setText(_translate("magnetism_signal3Dreconstruction", "Use Projection Matrices"))
        self.label_16.setText(_translate("magnetism_signal3Dreconstruction", "X"))
        self.label_17.setText(_translate("magnetism_signal3Dreconstruction", "Y"))
        self.label_18.setText(_translate("magnetism_signal3Dreconstruction", "Z"))
        self.label_22.setToolTip(_translate("magnetism_signal3Dreconstruction", "Number of iterations for the reconstruction algorithm"))
        self.label_22.setText(_translate("magnetism_signal3Dreconstruction", "Number iterations"))
        self.label_14.setText(_translate("magnetism_signal3Dreconstruction", "Output\n"
"path"))
        self.label_15.setToolTip(_translate("magnetism_signal3Dreconstruction", "Number of cells for the reconstruction in X, Y and Z.\n"
"It can be as larga as the number of rows and columns in the input tomogram.\n"
"If X or Y is 0, it takes the size of the absorption images. "))
        self.label_15.setText(_translate("magnetism_signal3Dreconstruction", "Number of\n"
"cells"))
        self.label_23.setToolTip(_translate("magnetism_signal3Dreconstruction", "Indicate if it is a continuous film."))
        self.label_23.setText(_translate("magnetism_signal3Dreconstruction", "Continuous film"))
        self.reconstruction_pushButton.setText(_translate("magnetism_signal3Dreconstruction", "Reconstruction+Registration"))
        self.registration_pushButton.setText(_translate("magnetism_signal3Dreconstruction", "Only registration"))
        self.visualization_pushButton.setText(_translate("magnetism_signal3Dreconstruction", "Visualization"))
        self.label_11.setText(_translate("magnetism_signal3Dreconstruction", "Copyright © 2024 ALBA-CELLS"))
