# -*- coding: utf-8 -*-
# Copyright (C) 2014-2025 ALBA Synchrotron
#
# Authors: A. Estela Herguedas Alonso, Joaquin Gomez Sanchez
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_magnetism(object):
    def setupUi(self, magnetism):
        magnetism.setObjectName("magnetism")
        magnetism.resize(780, 813)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("magnetism_preprocessing\\../magnetism_xmcd/ALBA_positiu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        magnetism.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(magnetism)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(magnetism)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(magnetism)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.horizontalLayout.addWidget(self.path_lineEdit)
        self.selectPath_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.selectPath_pushButton.setObjectName("selectPath_pushButton")
        self.horizontalLayout.addWidget(self.selectPath_pushButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.input_groupBox = QtWidgets.QGroupBox(magnetism)
        self.input_groupBox.setObjectName("input_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.input_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.selectTxt_radioButton = QtWidgets.QRadioButton(self.input_groupBox)
        self.selectTxt_radioButton.setObjectName("selectTxt_radioButton")
        self.gridLayout.addWidget(self.selectTxt_radioButton, 1, 0, 1, 1)
        self.selectTxt_lineEdit = QtWidgets.QLineEdit(self.input_groupBox)
        self.selectTxt_lineEdit.setEnabled(False)
        self.selectTxt_lineEdit.setObjectName("selectTxt_lineEdit")
        self.gridLayout.addWidget(self.selectTxt_lineEdit, 1, 1, 1, 1)
        self.selectTxt_pushButton = QtWidgets.QPushButton(self.input_groupBox)
        self.selectTxt_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectTxt_pushButton.sizePolicy().hasHeightForWidth())
        self.selectTxt_pushButton.setSizePolicy(sizePolicy)
        self.selectTxt_pushButton.setObjectName("selectTxt_pushButton")
        self.gridLayout.addWidget(self.selectTxt_pushButton, 1, 2, 1, 1)
        self.selectDB_radioButton = QtWidgets.QRadioButton(self.input_groupBox)
        self.selectDB_radioButton.setObjectName("selectDB_radioButton")
        self.gridLayout.addWidget(self.selectDB_radioButton, 3, 0, 1, 1)
        self.selectDB_lineEdit = QtWidgets.QLineEdit(self.input_groupBox)
        self.selectDB_lineEdit.setEnabled(False)
        self.selectDB_lineEdit.setObjectName("selectDB_lineEdit")
        self.gridLayout.addWidget(self.selectDB_lineEdit, 3, 1, 1, 1)
        self.selectDB_pushButton = QtWidgets.QPushButton(self.input_groupBox)
        self.selectDB_pushButton.setEnabled(False)
        self.selectDB_pushButton.setObjectName("selectDB_pushButton")
        self.gridLayout.addWidget(self.selectDB_pushButton, 3, 2, 1, 1)
        self.selectFolder_radioButton = QtWidgets.QRadioButton(self.input_groupBox)
        self.selectFolder_radioButton.setMinimumSize(QtCore.QSize(0, 28))
        self.selectFolder_radioButton.setChecked(True)
        self.selectFolder_radioButton.setObjectName("selectFolder_radioButton")
        self.gridLayout.addWidget(self.selectFolder_radioButton, 0, 0, 1, 1)
        self.selectPattern_radioButton = QtWidgets.QRadioButton(self.input_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectPattern_radioButton.sizePolicy().hasHeightForWidth())
        self.selectPattern_radioButton.setSizePolicy(sizePolicy)
        self.selectPattern_radioButton.setMinimumSize(QtCore.QSize(0, 28))
        self.selectPattern_radioButton.setObjectName("selectPattern_radioButton")
        self.gridLayout.addWidget(self.selectPattern_radioButton, 2, 0, 1, 1)
        self.selectPattern_lineEdit = QtWidgets.QLineEdit(self.input_groupBox)
        self.selectPattern_lineEdit.setEnabled(False)
        self.selectPattern_lineEdit.setObjectName("selectPattern_lineEdit")
        self.gridLayout.addWidget(self.selectPattern_lineEdit, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.delPrevExec_checkBox = QtWidgets.QCheckBox(self.input_groupBox)
        self.delPrevExec_checkBox.setObjectName("delPrevExec_checkBox")
        self.gridLayout_2.addWidget(self.delPrevExec_checkBox, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.input_groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(magnetism)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.subpixelAli_checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.subpixelAli_checkBox.setObjectName("subpixelAli_checkBox")
        self.gridLayout_9.addWidget(self.subpixelAli_checkBox, 1, 0, 1, 1)
        self.outlierThresh_checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.outlierThresh_checkBox.setObjectName("outlierThresh_checkBox")
        self.gridLayout_9.addWidget(self.outlierThresh_checkBox, 2, 0, 1, 1)
        self.outlierThresh_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.outlierThresh_doubleSpinBox.setEnabled(False)
        self.outlierThresh_doubleSpinBox.setProperty("value", 0.7)
        self.outlierThresh_doubleSpinBox.setObjectName("outlierThresh_doubleSpinBox")
        self.gridLayout_9.addWidget(self.outlierThresh_doubleSpinBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.algorithmAli_comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.algorithmAli_comboBox.setObjectName("algorithmAli_comboBox")
        self.algorithmAli_comboBox.addItem("")
        self.algorithmAli_comboBox.addItem("")
        self.algorithmAli_comboBox.addItem("")
        self.algorithmAli_comboBox.addItem("")
        self.algorithmAli_comboBox.addItem("")
        self.gridLayout_9.addWidget(self.algorithmAli_comboBox, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(magnetism)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.normFF_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.normFF_checkBox.setChecked(True)
        self.normFF_checkBox.setObjectName("normFF_checkBox")
        self.gridLayout_3.addWidget(self.normFF_checkBox, 0, 0, 1, 1)
        self.normBG_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.normBG_checkBox.setObjectName("normBG_checkBox")
        self.gridLayout_3.addWidget(self.normBG_checkBox, 1, 0, 1, 1)
        self.interpFF_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.interpFF_checkBox.setObjectName("interpFF_checkBox")
        self.gridLayout_3.addWidget(self.interpFF_checkBox, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(magnetism)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.saveAll_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.saveAll_checkBox.setToolTip("")
        self.saveAll_checkBox.setChecked(True)
        self.saveAll_checkBox.setObjectName("saveAll_checkBox")
        self.gridLayout_5.addWidget(self.saveAll_checkBox, 1, 0, 1, 1)
        self.cropStack_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.cropStack_checkBox.setChecked(True)
        self.cropStack_checkBox.setObjectName("cropStack_checkBox")
        self.gridLayout_5.addWidget(self.cropStack_checkBox, 0, 0, 1, 1)
        self.deleteProc_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.deleteProc_checkBox.setChecked(True)
        self.deleteProc_checkBox.setObjectName("deleteProc_checkBox")
        self.gridLayout_5.addWidget(self.deleteProc_checkBox, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_pushButton = QtWidgets.QPushButton(magnetism)
        self.start_pushButton.setObjectName("start_pushButton")
        self.horizontalLayout_4.addWidget(self.start_pushButton)
        self.visualization_pushButton = QtWidgets.QPushButton(magnetism)
        self.visualization_pushButton.setObjectName("visualization_pushButton")
        self.horizontalLayout_4.addWidget(self.visualization_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.notes = QtWidgets.QTextBrowser(magnetism)
        self.notes.setObjectName("notes")
        self.verticalLayout_2.addWidget(self.notes)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(magnetism)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(magnetism)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.retranslateUi(magnetism)
        self.buttonBox.accepted.connect(magnetism.accept) # type: ignore
        self.buttonBox.rejected.connect(magnetism.reject) # type: ignore
        self.selectTxt_radioButton.toggled['bool'].connect(self.selectTxt_lineEdit.setEnabled) # type: ignore
        self.selectTxt_radioButton.toggled['bool'].connect(self.selectTxt_pushButton.setEnabled) # type: ignore
        self.selectDB_radioButton.toggled['bool'].connect(self.selectDB_lineEdit.setEnabled) # type: ignore
        self.selectDB_radioButton.toggled['bool'].connect(self.selectDB_pushButton.setEnabled) # type: ignore
        self.selectPattern_radioButton.toggled['bool'].connect(self.selectPattern_lineEdit.setEnabled) # type: ignore
        self.outlierThresh_checkBox.clicked['bool'].connect(self.outlierThresh_doubleSpinBox.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(magnetism)
        magnetism.setTabOrder(self.path_lineEdit, self.selectPath_pushButton)
        magnetism.setTabOrder(self.selectPath_pushButton, self.selectTxt_radioButton)
        magnetism.setTabOrder(self.selectTxt_radioButton, self.selectTxt_lineEdit)
        magnetism.setTabOrder(self.selectTxt_lineEdit, self.selectTxt_pushButton)
        magnetism.setTabOrder(self.selectTxt_pushButton, self.selectDB_radioButton)
        magnetism.setTabOrder(self.selectDB_radioButton, self.selectDB_lineEdit)
        magnetism.setTabOrder(self.selectDB_lineEdit, self.selectDB_pushButton)
        magnetism.setTabOrder(self.selectDB_pushButton, self.normFF_checkBox)
        magnetism.setTabOrder(self.normFF_checkBox, self.interpFF_checkBox)
        magnetism.setTabOrder(self.interpFF_checkBox, self.normBG_checkBox)
        magnetism.setTabOrder(self.normBG_checkBox, self.cropStack_checkBox)
        magnetism.setTabOrder(self.cropStack_checkBox, self.saveAll_checkBox)
        magnetism.setTabOrder(self.saveAll_checkBox, self.start_pushButton)
        magnetism.setTabOrder(self.start_pushButton, self.visualization_pushButton)
        magnetism.setTabOrder(self.visualization_pushButton, self.notes)

    def retranslateUi(self, magnetism):
        _translate = QtCore.QCoreApplication.translate
        magnetism.setWindowTitle(_translate("magnetism", "MARTApp"))
        self.label.setToolTip(_translate("magnetism", "Many repetition images at different angles. Normally using 2 different polarizations. \n"
"xrm2hdf5 >> crop >> normalize >> align2D >> average >> [stack]"))
        self.label.setText(_translate("magnetism", "Preprocessing"))
        self.groupBox.setTitle(_translate("magnetism", "Path"))
        self.selectPath_pushButton.setText(_translate("magnetism", "Select path"))
        self.input_groupBox.setTitle(_translate("magnetism", "Input"))
        self.selectTxt_radioButton.setToolTip(_translate("magnetism", "Filename of the .txt script containing the commands used to perform the image acquisition by the BL09 TXM microscope."))
        self.selectTxt_radioButton.setText(_translate("magnetism", "File .txt"))
        self.selectTxt_pushButton.setText(_translate("magnetism", "Select"))
        self.selectDB_radioButton.setToolTip(_translate("magnetism", "Filename of the experiment database."))
        self.selectDB_radioButton.setText(_translate("magnetism", "Database .json"))
        self.selectDB_pushButton.setText(_translate("magnetism", "Select"))
        self.selectFolder_radioButton.setText(_translate("magnetism", "Folder"))
        self.selectPattern_radioButton.setToolTip(_translate("magnetism", "Tag pattern for filename interpretation e.g: angle_energy_repetition to parse values from filename."))
        self.selectPattern_radioButton.setText(_translate("magnetism", "Name pattern"))
        self.delPrevExec_checkBox.setText(_translate("magnetism", "Delete previous execution"))
        self.groupBox_4.setTitle(_translate("magnetism", "Alignment"))
        self.subpixelAli_checkBox.setText(_translate("magnetism", "Sub-pixel"))
        self.outlierThresh_checkBox.setText(_translate("magnetism", "Outlier threshold"))
        self.label_2.setText(_translate("magnetism", "Method"))
        self.algorithmAli_comboBox.setItemText(0, _translate("magnetism", "pyStackReg"))
        self.algorithmAli_comboBox.setItemText(1, _translate("magnetism", "Cross-Correlation Fourier"))
        self.algorithmAli_comboBox.setItemText(2, _translate("magnetism", "Cross-Correlation"))
        self.algorithmAli_comboBox.setItemText(3, _translate("magnetism", "Correlation Coefficient"))
        self.algorithmAli_comboBox.setItemText(4, _translate("magnetism", "Optical Flow"))
        self.groupBox_2.setTitle(_translate("magnetism", "Normalization"))
        self.normFF_checkBox.setToolTip(_translate("magnetism", "Normalize using flat-field."))
        self.normFF_checkBox.setText(_translate("magnetism", "Flat-field"))
        self.normBG_checkBox.setToolTip(_translate("magnetism", "Normalize using background."))
        self.normBG_checkBox.setText(_translate("magnetism", "Background"))
        self.interpFF_checkBox.setToolTip(_translate("magnetism", "Missing flat-field will be interpolated."))
        self.interpFF_checkBox.setText(_translate("magnetism", "Interpolate Flat-field"))
        self.groupBox_3.setTitle(_translate("magnetism", "Output"))
        self.saveAll_checkBox.setText(_translate("magnetism", "Save all in a single file (stack, flat-field, background)"))
        self.cropStack_checkBox.setToolTip(_translate("magnetism", "Crop output images."))
        self.cropStack_checkBox.setText(_translate("magnetism", "Crop stack"))
        self.deleteProc_checkBox.setText(_translate("magnetism", "Delete intermediate processing HDF5 files"))
        self.start_pushButton.setToolTip(_translate("magnetism", "Execute pipeline \"magnetism\""))
        self.start_pushButton.setText(_translate("magnetism", "GO!"))
        self.visualization_pushButton.setToolTip(_translate("magnetism", "Open HDF5 with Napari"))
        self.visualization_pushButton.setText(_translate("magnetism", "Visualization"))
        self.label_3.setText(_translate("magnetism", "Copyright © 2024 ALBA-CELLS"))
