# -*- coding: utf-8 -*-
# Copyright (C) 2014-2025 ALBA Synchrotron
#
# Authors: A. Estela Herguedas Alonso, Joaquin Gomez Sanchez
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MagnetismMISTRALGUI(object):
    def setupUi(self, MagnetismMISTRALGUI):
        MagnetismMISTRALGUI.setObjectName("MagnetismMISTRALGUI")
        MagnetismMISTRALGUI.resize(408, 469)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MagnetismMISTRALGUI)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(MagnetismMISTRALGUI)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ALBALogo_label = QtWidgets.QLabel(MagnetismMISTRALGUI)
        self.ALBALogo_label.setMaximumSize(QtCore.QSize(100, 50))
        self.ALBALogo_label.setText("")
        self.ALBALogo_label.setScaledContents(True)
        self.ALBALogo_label.setObjectName("ALBALogo_label")
        self.horizontalLayout_2.addWidget(self.ALBALogo_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.magnetismXMCDTS1_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnetismXMCDTS1_pushButton.sizePolicy().hasHeightForWidth())
        self.magnetismXMCDTS1_pushButton.setSizePolicy(sizePolicy)
        self.magnetismXMCDTS1_pushButton.setObjectName("magnetismXMCDTS1_pushButton")
        self.gridLayout.addWidget(self.magnetismXMCDTS1_pushButton, 4, 0, 1, 1)
        self.magnetismTS2_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnetismTS2_pushButton.sizePolicy().hasHeightForWidth())
        self.magnetismTS2_pushButton.setSizePolicy(sizePolicy)
        self.magnetismTS2_pushButton.setObjectName("magnetismTS2_pushButton")
        self.gridLayout.addWidget(self.magnetismTS2_pushButton, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(MagnetismMISTRALGUI)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.ManualAliTS2_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManualAliTS2_pushButton.sizePolicy().hasHeightForWidth())
        self.ManualAliTS2_pushButton.setSizePolicy(sizePolicy)
        self.ManualAliTS2_pushButton.setObjectName("ManualAliTS2_pushButton")
        self.gridLayout.addWidget(self.ManualAliTS2_pushButton, 5, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pathTS2_lineEdit = QtWidgets.QLineEdit(MagnetismMISTRALGUI)
        self.pathTS2_lineEdit.setObjectName("pathTS2_lineEdit")
        self.horizontalLayout_4.addWidget(self.pathTS2_lineEdit)
        self.selectPathTS2_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        self.selectPathTS2_pushButton.setObjectName("selectPathTS2_pushButton")
        self.horizontalLayout_4.addWidget(self.selectPathTS2_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.ManualAliTS1_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManualAliTS1_pushButton.sizePolicy().hasHeightForWidth())
        self.ManualAliTS1_pushButton.setSizePolicy(sizePolicy)
        self.ManualAliTS1_pushButton.setObjectName("ManualAliTS1_pushButton")
        self.gridLayout.addWidget(self.ManualAliTS1_pushButton, 5, 0, 1, 1)
        self.magnetismTS1_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnetismTS1_pushButton.sizePolicy().hasHeightForWidth())
        self.magnetismTS1_pushButton.setSizePolicy(sizePolicy)
        self.magnetismTS1_pushButton.setObjectName("magnetismTS1_pushButton")
        self.gridLayout.addWidget(self.magnetismTS1_pushButton, 3, 0, 1, 1)
        self.magnetismXMCDTS2_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnetismXMCDTS2_pushButton.sizePolicy().hasHeightForWidth())
        self.magnetismXMCDTS2_pushButton.setSizePolicy(sizePolicy)
        self.magnetismXMCDTS2_pushButton.setObjectName("magnetismXMCDTS2_pushButton")
        self.gridLayout.addWidget(self.magnetismXMCDTS2_pushButton, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(MagnetismMISTRALGUI)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pathTS1_lineEdit = QtWidgets.QLineEdit(MagnetismMISTRALGUI)
        self.pathTS1_lineEdit.setObjectName("pathTS1_lineEdit")
        self.horizontalLayout_3.addWidget(self.pathTS1_lineEdit)
        self.selectPathTS1_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        self.selectPathTS1_pushButton.setObjectName("selectPathTS1_pushButton")
        self.horizontalLayout_3.addWidget(self.selectPathTS1_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.magnetism2Dreconstruction_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnetism2Dreconstruction_pushButton.sizePolicy().hasHeightForWidth())
        self.magnetism2Dreconstruction_pushButton.setSizePolicy(sizePolicy)
        self.magnetism2Dreconstruction_pushButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.magnetism2Dreconstruction_pushButton.setObjectName("magnetism2Dreconstruction_pushButton")
        self.verticalLayout.addWidget(self.magnetism2Dreconstruction_pushButton)
        self.absorption3Dreconstruction_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.absorption3Dreconstruction_pushButton.sizePolicy().hasHeightForWidth())
        self.absorption3Dreconstruction_pushButton.setSizePolicy(sizePolicy)
        self.absorption3Dreconstruction_pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.absorption3Dreconstruction_pushButton.setObjectName("absorption3Dreconstruction_pushButton")
        self.verticalLayout.addWidget(self.absorption3Dreconstruction_pushButton)
        self.magnetism3Dreconstruction_pushButton = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnetism3Dreconstruction_pushButton.sizePolicy().hasHeightForWidth())
        self.magnetism3Dreconstruction_pushButton.setSizePolicy(sizePolicy)
        self.magnetism3Dreconstruction_pushButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.magnetism3Dreconstruction_pushButton.setObjectName("magnetism3Dreconstruction_pushButton")
        self.verticalLayout.addWidget(self.magnetism3Dreconstruction_pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(MagnetismMISTRALGUI)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(MagnetismMISTRALGUI)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(MagnetismMISTRALGUI)
        self.pushButton_4.clicked.connect(MagnetismMISTRALGUI.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MagnetismMISTRALGUI)

    def retranslateUi(self, MagnetismMISTRALGUI):
        _translate = QtCore.QCoreApplication.translate
        MagnetismMISTRALGUI.setWindowTitle(_translate("MagnetismMISTRALGUI", "MARTApp"))
        self.label_3.setText(_translate("MagnetismMISTRALGUI", "Magnetic Analysis & Reconstruction of Tomographies App"))
        self.magnetismXMCDTS1_pushButton.setToolTip(_translate("MagnetismMISTRALGUI", "Execute pipeline \"magnetism_xmcd\" for tilt series 1"))
        self.magnetismXMCDTS1_pushButton.setText(_translate("MagnetismMISTRALGUI", "XMCD"))
        self.magnetismTS2_pushButton.setToolTip(_translate("MagnetismMISTRALGUI", "Execute pipeline \"magnetism\" for tilt series 2"))
        self.magnetismTS2_pushButton.setText(_translate("MagnetismMISTRALGUI", "Preprocessing"))
        self.label_2.setToolTip(_translate("MagnetismMISTRALGUI", "Location of the data of the second (rotated) tilt series."))
        self.label_2.setText(_translate("MagnetismMISTRALGUI", "Tilt Series 2"))
        self.ManualAliTS2_pushButton.setToolTip(_translate("MagnetismMISTRALGUI", "Perform manual alignment for tilt series 2"))
        self.ManualAliTS2_pushButton.setText(_translate("MagnetismMISTRALGUI", "Manual Alignment"))
        self.selectPathTS2_pushButton.setText(_translate("MagnetismMISTRALGUI", "Select path"))
        self.ManualAliTS1_pushButton.setToolTip(_translate("MagnetismMISTRALGUI", "Perform manual alignment for tilt series 1"))
        self.ManualAliTS1_pushButton.setText(_translate("MagnetismMISTRALGUI", "Manual Alignment"))
        self.magnetismTS1_pushButton.setToolTip(_translate("MagnetismMISTRALGUI", "Execute pipeline \"magnetism\" for tilt series 1"))
        self.magnetismTS1_pushButton.setText(_translate("MagnetismMISTRALGUI", "Preprocessing"))
        self.magnetismXMCDTS2_pushButton.setToolTip(_translate("MagnetismMISTRALGUI", "Execute pipeline \"magnetism_xmcd\" for tilt series 2"))
        self.magnetismXMCDTS2_pushButton.setText(_translate("MagnetismMISTRALGUI", "XMCD"))
        self.label.setToolTip(_translate("MagnetismMISTRALGUI", "Location of the data of the first tilt series."))
        self.label.setText(_translate("MagnetismMISTRALGUI", "Tilt Series 1"))
        self.selectPathTS1_pushButton.setText(_translate("MagnetismMISTRALGUI", "Select path"))
        self.magnetism2Dreconstruction_pushButton.setToolTip(_translate("MagnetismMISTRALGUI", "Execute pipeline \"magnetism_2Dreconstruction\""))
        self.magnetism2Dreconstruction_pushButton.setText(_translate("MagnetismMISTRALGUI", "Magnetic reconstruction of 2D samples"))
        self.absorption3Dreconstruction_pushButton.setText(_translate("MagnetismMISTRALGUI", "Absorption reconstruction of 3D samples"))
        self.magnetism3Dreconstruction_pushButton.setText(_translate("MagnetismMISTRALGUI", "Magnetic reconstruction of 3D samples"))
        self.label_4.setText(_translate("MagnetismMISTRALGUI", "Copyright © 2024 ALBA-CELLS"))
        self.pushButton_4.setText(_translate("MagnetismMISTRALGUI", "Close"))
